# golangci-lint configuration for golangci-lint v2.5.0
# Simplified config focusing on linters available in v2.5.0

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  max-same-issues: 50
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - bodyclose
        - dupl
        - errcheck
        - funlen
        - goconst
        - gosec
        - noctx
    # Exclude standard error handling
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    # Ignore package comment requirements for main packages
    - path: main\.go
      text: "should have a package comment"
      linters:
        - revive

linters:
  disable-all: true
  enable:
    - asciicheck      # Check for non-ASCII identifiers
    - bidichk         # Check for dangerous unicode character sequences
    - bodyclose       # Check HTTP response body is closed
    - cyclop          # Check function and package cyclomatic complexity
    - dupl            # Code clone detection
    - durationcheck   # Check for two durations multiplied together
    - errcheck        # Check for unchecked errors
    - errorlint       # Find code that will cause problems with the error wrapping scheme
    - exhaustive      # Check exhaustiveness of enum switch statements
    - funlen          # Detect long functions
    - goconst         # Find repeated strings that could be constants
    - gocritic        # Comprehensive Go source code linter
    - gocyclo         # Compute cyclomatic complexity
    - godox           # Detect FIXME, TODO and other comment tags
    - gosec           # Security problems
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - misspell        # Find commonly misspelled English words
    - nakedret        # Find naked returns in functions greater than specified length
    - nilerr          # Find code returning nil even if it checks err != nil
    - noctx           # Find HTTP requests without context.Context
    - nolintlint      # Reports ill-formed or insufficient nolint directives
    - predeclared     # Find code that shadows one of Go's predeclared identifiers
    - revive          # Fast, configurable, extensible, flexible, and beautiful linter
    - staticcheck     # Go vet on steroids
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters
    - unused          # Check for unused constants, variables, functions and types
    - wastedassign    # Find wasted assignment statements
    - whitespace      # Check for unnecessary blank lines

linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0

  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/golang/protobuf"
            desc: "Use google.golang.org/protobuf instead"
          - pkg: "github.com/satori/go.uuid"
            desc: "Use github.com/google/uuid instead"
          - pkg: "io/ioutil"
            desc: "Use io and os packages instead"

  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true

  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint

  gosec:
    excludes:
      - G115

  govet:
    enable-all: true
    settings:
      shadow:
        strict: false
    disable:
      - fieldalignment
      - shadow

  nakedret:
    max-func-lines: 0

  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: true
    require-specific: true

  revive:
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]
